Add import an object from CSV file and Query list page
digi-serve/plugin_ABDesigner pull request #1
Opened 2021-11-02 05:05 UTC by wongpratan

2021-11-08 09:59 UTC, Hiro-Nakamura requested changes
OK, it looks like you are trying to pull into the ```forms/``` both a copy of the ```core``` and the ```platform``` code.  

But in the plugin, we are trying to not pull in any of the code already present in the ```ab_platform_web``` codebase.  

Let's talk when your in the office again about what your trying to do with these files and how we can accomplish it without duplicating the code here too.

2021-11-08 11:00 UTC, Hiro-Nakamura requested changes
Good job on the unit tests.  I'll have to go back and copy what you did for mine ... unless you want to do it ... :)

2021-11-11 04:53 UTC, wongpratan commented on src/rootPages/Designer/ui_work.js
> +   const AppQueryWorkspace = new (UI_Work_Query(AB))();
If we export UI_Work_Object is a class instead of a instance, then it is easier to mock up in unit test.

2021-11-30 05:16 UTC, Hiro-Nakamura requested changes
Let's update some of these changes and talk about Unit Tests in person.

2021-11-30 05:16 UTC, Hiro-Nakamura commented on test/rootPages/Designer/ui_work_object_list_newObject_csv.test.js
> +   it(".constructor - should set valid properties", function () {
Hey, when you come in on Wednesday, let's have a talk about unit tests.

2022-01-04 09:05 UTC, wongpratan commented on src/rootPages/Designer/ui_work_object_list_newObject_csv.js
> +         subTasks = subTasks.then(() => objModel.createAll(rowDatas));
https://github.com/digi-serve/plugin_ABDesigner/pull/1#discussion_r744588138

2022-01-04 09:05 UTC, wongpratan commented on src/rootPages/Designer/ui_work_object_list_newObject_csv.js
> +               return objModel.create(rowData);
https://github.com/digi-serve/plugin_ABDesigner/pull/1#discussion_r758922197

2022-01-19 05:04 UTC, merged