New adding field type UI
digi-serve/plugin_ABDesigner pull request #12
Opened 2022-02-07 09:38 UTC by guyyoo

2022-02-09 02:55 UTC, jamesduncan requested changes

2022-02-09 02:55 UTC, jamesduncan commented on src/rootPages/Designer/ui_work_object_workspace_popupNewDataField.js
> +                     label: L("<span>Choose Field-Type</span>"),
Do we need the <span> tag or can it be removed?

2022-02-09 02:55 UTC, jamesduncan commented on src/rootPages/Designer/ui_work_object_workspace_popupNewDataField.js
> +                           label: L("<span class=\"webix_icon\"><i class=\"nomargin fa fa-expand\"></i></span>"),
I think if we are not going to translate this to another language you do not have to wrap in the L() function.

2022-02-09 02:55 UTC, jamesduncan commented on src/rootPages/Designer/ui_work_object_workspace_popupNewDataField.js
> +                           label: L("<span class=\"webix_icon\"><i class=\"nomargin fa fa-compress\"></i></span>"),
I think if we are not going to translate this to another language you do not have to wrap in the L() function.

2022-02-09 02:55 UTC, jamesduncan commented on src/rootPages/Designer/ui_work_object_workspace_popupNewDataField.js
> +                           label: L("<span class=\"webix_icon\"><i class=\"nomargin fa fa-times\"></i></span>"),
I think if we are not going to translate this to another language you do not have to wrap in the L() function.

2022-02-09 02:55 UTC, jamesduncan commented on src/rootPages/Designer/ui_work_object_workspace_popupNewDataField.js
> +                           placeholder: "Search by title...",
Wrap this in the L() function so we can translate it later... 

`placeholder: L("Search by title..."),`

2022-02-09 02:55 UTC, jamesduncan commented on src/rootPages/Designer/ui_work_object_workspace_popupNewDataField.js
> +            this.submenus.push({ id: menuName, icon: `nomargin fa fa-${icon}`,  labelNickName: L(menuName), label: L(menuName)});
labelNickName and label seem to be the same, do we use them in different ways?

2022-02-09 02:55 UTC, jamesduncan commented on src/rootPages/Designer/ui_work_object_workspace_popupNewDataField.js
> +         $$(this.ids.title).setValue(L(`<span>Create Field: ${name}</span>`));
We can translate the first part but the "name" will have its translation stored elsewhere so try this...

`$$(this.ids.title).setValue(L("Create Field:") + " " + name");`

2022-02-09 02:55 UTC, jamesduncan commented on src/rootPages/Designer/ui_work_object_workspace_popupNewDataField.js
> +         $$(this.ids.title).setValue(L(`<span>Choose Field-Type</span>`));
Remove span tag.

2022-02-09 02:55 UTC, jamesduncan commented on src/rootPages/Designer/ui_work_object_workspace_popupNewDataField.js
> +         $$(this.ids.buttonSave).define("label", L("<span class=\"text\">Create</span>"));
Remove span tag.

2022-02-09 02:55 UTC, jamesduncan commented on src/rootPages/Designer/ui_work_object_workspace_popupNewDataField.js
> +         $$(this.ids.title).setValue(L(`<span>Create Field: ${fieldTypeName}</span>`));
Remove span tag.

2022-02-09 02:55 UTC, jamesduncan commented on src/rootPages/Designer/ui_work_object_workspace_popupNewDataField.js
> +         $$(this.ids.buttonSave).define("label", L("<span class=\"text\">Save</span>"));
Remove span tag.

2022-02-09 02:55 UTC, jamesduncan commented on src/rootPages/Designer/ui_work_object_workspace_popupNewDataField.js
> +                     label: L("<span>Choose Field-Type</span>"),
label: L("Choose Field-Type"),
label: "<span>" + L("Chooose Field-Type") + "</span>",

2022-02-14 03:09 UTC, jamesduncan approved these changes

2022-02-14 03:54 UTC, nh758 approved these changes

2022-02-14 03:54 UTC, merged