Datacollection site
digi-serve/plugin_ABDesigner pull request #28
Opened 2022-04-01 06:29 UTC by guyyoo

2022-04-02 05:12 UTC, Hiro-Nakamura requested changes
A few more changes

2022-04-02 05:12 UTC, Hiro-Nakamura commented on src/rootPages/Designer/ui_work_datacollection_workspace_properties.js
> +         const filterValues = this.FilterComponent.getValue();
If we change `this.FilterComponent` to use the `filtercomplexNew()` like I mentioned earlier, that now has a `.isConditionComplete()` method that does this rule check itself.

2022-04-02 05:12 UTC, Hiro-Nakamura commented on src/rootPages/Designer/ui_work_datacollection_workspace_properties.js
> +                  f.rule == "is_current_user" ||
it looks like the `FilterComplex.isConditionComplete()` method isn't as complete as this check here.  Go ahead and include these checks into there as well.

2022-04-05 06:43 UTC, guyyoo commented on src/rootPages/Designer/ui_work_datacollection_workspace_properties.js
> +                  value: L("[Current User]"),
Ok, I will bring this up on next standup.

2022-04-07 07:40 UTC, Hiro-Nakamura requested changes
Hey, did you move those additional `isConditionComplete()` conditions into the `FilterComplex` object?

If so, then make this simple string building change and we are good to go.

2022-04-07 07:40 UTC, Hiro-Nakamura commented on src/rootPages/Designer/ui_work_datacollection_workspace_properties.js
> +         this._templateListItem = [
let's change this sort of string building into the newer : 
```
this._templateListItem = `
   <div class='ab-page-list-item'>
     {common.icon()} <span ... > #label# #hasDataCollection#
   </div>
`
```

2022-04-07 10:17 UTC, merged