Service Reset Password URL
digi-serve/plugin_ABDesigner pull request #32
Opened 2022-04-29 08:45 UTC by guyyoo

2022-05-02 03:16 UTC, wongpratan commented on src/rootPages/Designer/properties/process/ABProcessTaskService.js
> +         values.key = key || this.key;
Should It be 
`key ?? this.key; `
instead ?

2022-05-02 03:16 UTC, wongpratan commented on src/rootPages/Designer/properties/process/ABProcessTaskService.js
> +         obj.name = $name.getValue() || "";
??

2022-05-02 03:17 UTC, wongpratan commented on src/rootPages/Designer/properties/process/ABProcessTaskService.js
> +         $name.setValue(element.label || "");
`$name.setValue(element.label ?? "");`

2022-05-02 03:17 UTC, wongpratan commented on src/rootPages/Designer/properties/process/ABProcessTaskServiceGetResetPasswordUrl.js
> +         obj.url = $url.getValue() || "";
:)

2022-05-02 03:49 UTC, wongpratan approved these changes

2022-05-05 09:10 UTC, Hiro-Nakamura requested changes

2022-05-05 09:10 UTC, Hiro-Nakamura commented on src/rootPages/Designer/properties/process/ABProcessTaskServiceInsertRecord.js
> +            value: `Set by the paremeter of a Query task`,
this should be a `L("Set by the parameter of a Query task")`   <--- also notice spelling of `parameter`

2022-05-05 09:10 UTC, Hiro-Nakamura commented on src/rootPages/Designer/properties/process/ABProcessTaskServiceInsertRecord.js
> +      propertiesStash() {
our new Property views use `populate()`  and `values()`  now.  refactor this old `propertiesStash()` to be `values()`

2022-05-05 09:10 UTC, Hiro-Nakamura commented on src/rootPages/Designer/properties/process/ABProcessTaskServiceInsertRecord.js
> +      propertiesStash() {
or just get rid of this if it is unnecessary

2022-05-05 09:10 UTC, Hiro-Nakamura commented on src/rootPages/Designer/properties/PropertyManager.js
> -      require("./process/ABProcessParticipant.js"),
Do we not need this one anymore?

2022-05-06 04:31 UTC, guyyoo commented on src/rootPages/Designer/properties/process/ABProcessTaskServiceInsertRecord.js
> +         const objectList = this.AB.objects().map((o) => {
I already talked with him. Yes, we need to see only the objects in the current app we work on. I am going to change this.

2022-05-11 05:40 UTC, Hiro-Nakamura requested changes
fix some of those edits in the PropertyManager and then should be good to go.

2022-05-11 09:12 UTC, merged